{
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
    ../../modules/programs.nix
  ];
  # Put your username here for login
  users.users.user.name = "arne";

  clan.core.networking.targetHost = "root@tempy";

  # You can get your disk id by running the following command on the installer:
  # Replace <IP> with the IP of the installer printed on the screen or by running the `ip addr` command.
  # ssh root@10.10.10.8 lsblk --output NAME,ID-LINK,FSTYPE,SIZE,MOUNTPOINT
  disko.devices.disk.main.device = "/dev/disk/by-id/ata-ShiJi_256GB_RE000000000000000721";

  /*
    After tempy is deployed, uncomment the following line
    This will allow cube to share the VPN overlay network with tempy
    The networkId is generated by the first deployment of tempy
  */
  clan.core.networking.zerotier.networkId = builtins.readFile ../../vars/per-machine/cube/zerotier/zerotier-network-id/value;
}
