{
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
  ];
  # Put your username here for login
  users.users.user.name = "arne";
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJkHOi39HCigHCOneTKIiY+C809n6d3sNHd3hoy2Uq21 Warden"
  ];

  # Set this for clan commands use ssh i.e. `clan machines update`
  # If you change the hostname, you need to update this line to root@<new-hostname>
  # This only works however if you have avahi running on your admin machine else use IP
  clan.core.networking.targetHost = "root@10.10.10.8";

  # You can get your disk id by running the following command on the installer:
  # Replace <IP> with the IP of the installer printed on the screen or by running the `ip addr` command.
  # ssh root@10.10.10.8 lsblk --output NAME,ID-LINK,FSTYPE,SIZE,MOUNTPOINT
  disko.devices.disk.main.device = "/dev/disk/by-id/ata-ShiJi_256GB_RE000000000000000721";

  /*
    After tempo is deployed, uncomment the following line
    This will allow cube to share the VPN overlay network with tempo
    The networkId is generated by the first deployment of tempo
  */
  # clan.core.networking.zerotier.networkId = builtins.readFile ../../vars/per-machine/jon/zerotier/zerotier-network-id/value;
  #
}
