{
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
    ../../modules/programs.nix
  ];

  clan.core.networking.targetHost = "root@tempy";

  # You can get your disk id by running the following command on the installer:
  # Replace <IP> with the IP of the installer printed on the screen or by running the `ip addr` command.
  # ssh root@10.10.10.8 lsblk --output NAME,ID-LINK,FSTYPE,SIZE,MOUNTPOINT
  disko.devices.disk.main.device = "/dev/disk/by-id/ata-ShiJi_256GB_RE000000000000000721";

  /*
    After tempy is deployed, uncomment the following line
    This will allow cube to share the VPN overlay network with tempy
    The networkId is generated by the first deployment of tempy
  */
  clan.core.networking.zerotier.networkId = builtins.readFile ../../vars/per-machine/cube/zerotier/zerotier-network-id/value;
  users.users.oystein = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "input"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCP8JGuz4TFe+MtKwreQqcwE/wTNwv9zgq9KU3cqQqvluFQm1x9H3VAa3HjurnLqSWkZPkS+JjuorspEzzMw95HnUAME9BJ4glGBDjUZSHeyAZXm5SHAyHfp7vgJRzHMKIid5CKhIj8mvWwVTW0ncGkiwnyrXCTFchvhqfnDu8cS0k/Wu9Kxmo/cOhDTCe5V1zRwD5NNVw+3wHmvYL+LEKtB2FVqhbX36Q7xVzKcpF/1dkBYjuKMUYkCarfjosjb7TN9L3D5tKCy8yAJQFqyNLXzZCfgtxtFINRkg7kGNTmzMG9pdsTItjvqN8dgY/ifxwKdF29bSSx1d3uy1264heGDOCp1qtuEtf9iZgIB5xA1t4k7bjIb/iYMp/wLFk2iRTc5WT8K3Gs7mqXzHKVjqy3InAdGmWjyy8b9EDiRD1lyjnf/T2yhaXzboKTxKT2ga4ctctQup3DtJHSObHUO5WuWnD/MQjsJmQ7W2VYDDbpJPq63XljuIE6sslRRzkoj98= oystein@Yoga2"
    ];
  };
   services.unifi = {
    enable = true;
    openFirewall = true;
  };
}
